### ISSUE TITLE
Set Selenium default Date time format to English 

### ISSUE THREAD

**Issue by lacribeiro11** [lacribeiro11/swt#15]
In fhcampuswien.ac.at.stepdefinitions.ExampleStepDefinitions#getFirstDayOfNextMonthDate
Change this:
`return nextMonth.format(DateTimeFormatter.ofPattern("dd.MM.yyyy"));`
to this
`return nextMonth.format(DateTimeFormatter.ofPattern("dd MMMM yyyy", new Locale("en")));`

**Comment by den-netizen** [comment]
Current date time format is correct: Th, 01.07.2021 is the date time format on https://fahrplan.oebb.at/bin/query.exe/en?
